export enum ProductTypeEnum {
  CERTIFIED_DEPOSIT_TERM = 'CDT',
  CREDIT = 'CREDITO',
  CREDIT_CARD = 'TARJETA DE CREDITO',
  CURRENT_ACCOUNT = 'CUENTA CORRIENTE',
  DEPOSIT_ACCOUNT = 'CUENTA AHORROS',
}
